### ISSUE TITLE
Per-app bandwidth usage?

### ISSUE THREAD

**Issue by Pictor13** [objective-see/Netiquette#2]
I know that is a little bit out of the Netiquette's scope, but I was wondering if the app could be able to monitor also the bandwidth usage of the different applications.

It's not strictly for security but that would give more insight on the network use
(in my specific case I can see an unusual total bandwidth use, via a vpn client; but I can't find out what process is using so much bandwidth, and Activity Monitor doesn't show bandwidth usage either).

Any plan to keep on with the development and maybe add this info per-app/-process?

Or, in negative case, what could be a good OSS that can provide such monitoring?

Thanks for your great job non the less =)

**Comment by objective-see** [comment]
This has been added in v2.0+ 🤗
(https://github.com/objective-see/Netiquette/releases/tag/v2.0.0)
