### ISSUE TITLE
Suggest adding configurable UI padding and margin

### ISSUE THREAD

**Issue by unphased** [objective-see/Netiquette#5]
The visual design is such that even when I maximize the window on my 16 inch macbook, I can only show 19 items on screen at a time. Not only is the font much bigger than needed, around 70% of the vertical space available is white space. I would like to be able to configure this. It would be possible to comfortably fit 50 or so items. 

Use case: Network Monitor of Lulu

**Comment by objective-see** [comment]
Added in v2.1.0: https://github.com/objective-see/Netiquette/releases/tag/v2.1.0
...adjust via View-> Zoom In / Zoom Out or ⌘+ / ⌘-
